# Declaring class + obfuscated field name = restored semantic field name.
# These aliases are used to update subclasses and same-class cross-instance access.
com.bstek.urule.action.AbstractAction.a=debug
com.bstek.urule.builder.AbstractBuilder.a=applicationContext
com.bstek.urule.builder.AbstractBuilder.b=resourceBuilders
com.bstek.urule.parse.AbstractRuleParser.a=lhsParser
com.bstek.urule.parse.AbstractRuleParser.b=rhsParser
com.bstek.urule.parse.AbstractRuleParser.c=otherParser
com.bstek.urule.parse.ActionParser.a=valueParser
com.bstek.urule.parse.PredefinesParser.a=valueParser
com.bstek.urule.runtime.AbstractWorkingMemory.a=logManager
com.bstek.urule.runtime.AbstractWorkingMemory.b=factManager
com.bstek.urule.runtime.AbstractWorkingMemory.c=ruleExecution
com.bstek.urule.runtime.AbstractWorkingMemory.d=knowledgeSession
com.bstek.urule.runtime.AbstractWorkingMemory.e=predefineValueMap
com.bstek.urule.runtime.AbstractWorkingMemory.f=sessionValueMap
com.bstek.urule.runtime.FactManager.g=factListMap
com.bstek.urule.runtime.execution.AbstractExecution.a=agenda
com.bstek.urule.runtime.execution.AbstractExecution.b=factManager
com.bstek.urule.runtime.execution.AbstractExecution.c=monitorManager
com.bstek.urule.runtime.execution.AbstractExecution.d=knowledgeSession
com.bstek.urule.runtime.execution.AbstractExecution.e=reteInstanceList
com.bstek.urule.runtime.execution.AbstractExecution.f=predefineExecutionUnits
com.bstek.urule.runtime.log.DataLog.a=msg
